name: Build, Test and Deploy to Prod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build and test code
      run: |
        cargo build --verbose
        cargo test --verbose

    - name: Extract version and name from Cargo.toml
      id: app-info
      run: |
        name=$(grep '^name\s*=' Cargo.toml | head -n1 | sed -E 's/name\s*=\s*"([^"]+)"/\1/')
        version=$(grep '^version\s*=' Cargo.toml | head -n1 | sed -E 's/version\s*=\s*"([^"]+)"/\1/')
        echo "APP_NAME=$name" >> "$GITHUB_OUTPUT"
        echo "APP_VERSION=$version" >> "$GITHUB_OUTPUT"
    - name: Debug extracted values
      run: |
        echo "App name: ${{ steps.app-info.outputs.APP_NAME }}"
        echo "Version: ${{ steps.app-info.outputs.APP_VERSION }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set output
      id: setter
      run: |
        echo "foo=bar" >> "$GITHUB_OUTPUT"

    - name: Build and push Docker images
      uses: docker/bake-action@v6
      with:
        push: true
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max
          *.platform=linux/arm/v8
          *.tags=${{ secrets.DOCKER_USERNAME }}/${{ steps.app-info.outputs.APP_NAME }}:${{ steps.app-info.outputs.APP_VERSION }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.RASPI_PRIVATE_SSH_KEY }}" > ~/.ssh/raspi_key
        chmod 600 ~/.ssh/raspi_key

    - name: Copy docker-compose.yml to raspi
      run:  scp -i ~/.ssh/raspi_key -o StrictHostKeyChecking=no docker-compose.yml daniel@${{ secrets.RASPI_IP }}:~

    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.RASPI_IP }}
        username: ${{ secrets.RASPI_USER }}
        key: ${{ secrets.RASPI_PRIVATE_SSH_KEY }}
        port: 22
        command_timeout: 30m
        script: |
          cd ~
          docker compose down
          docker compose pull
          docker compose up -d